[features]
seeds = false
skip-lint = false

[programs.localnet]
#keychain = "KeyNfJK4cXSjBof8Tg1aEDChUMea4A7wCzLweYFRAoN"
#keychain = "Key3oJGUxKaddvMRAKbyYVbE8Pf3ycrH8hyZxa7tVCo"
keychain = "keyKitXGRWbPhF7RkMhNk47CqcFWPqAhMuMjVwapS3K"
profile = "ProoXffuU4NJWstjWgFYqauFFatDMG9xHETuRMjKMLt"
yardsale = "dYaMxY3mLDYRQV68tgiV7gfPUC4eNzvEjvrDYSy4itq"

[programs.devnet]
#keychain = "KeyNfJK4cXSjBof8Tg1aEDChUMea4A7wCzLweYFRAoN"
#keychain = "Key3oJGUxKaddvMRAKbyYVbE8Pf3ycrH8hyZxa7tVCo"
keychain = "keyKitXGRWbPhF7RkMhNk47CqcFWPqAhMuMjVwapS3K"
profile = "ProoXffuU4NJWstjWgFYqauFFatDMG9xHETuRMjKMLt"
yardsale = "dYaMxY3mLDYRQV68tgiV7gfPUC4eNzvEjvrDYSy4itq"

[programs.mainnet]
#keychain = "KeyNfJK4cXSjBof8Tg1aEDChUMea4A7wCzLweYFRAoN"
#keychain = "Key3oJGUxKaddvMRAKbyYVbE8Pf3ycrH8hyZxa7tVCo"
keychain = "keyKitXGRWbPhF7RkMhNk47CqcFWPqAhMuMjVwapS3K"
profile = "ProoXffuU4NJWstjWgFYqauFFatDMG9xHETuRMjKMLt"
yardsale = "dYaMxY3mLDYRQV68tgiV7gfPUC4eNzvEjvrDYSy4itq"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"
#wallet = "~/.config/solana/devkey.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pnfts.ts"
test-pnfts = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pnfts.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/keychkain.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
#test-keychain = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/keychain.ts"
#test-yardsale = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/yardsale.ts"

